name: Build Python App for macOS

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          arch -${{ matrix.arch }} python -m pip install --upgrade pip
          arch -${{ matrix.arch }} pip install -r requirements.txt
          arch -${{ matrix.arch }} pip install pyinstaller

      - name: Build executable
        run: |
          arch -${{ matrix.arch }} pyinstaller --onefile \
            --distpath ./dist \
            --name "app_${GITHUB_REF_NAME}_macos_${{ matrix.arch }}" \
            src/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app_${{ github.ref_name }}_macos_${{ matrix.arch }}
          path: dist/app_${{ github.ref_name }}_macos_${{ matrix.arch }}