name: Build Application Binaries Artifacts
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          arch -${{ matrix.arch }} python -m pip install --upgrade pip
          arch -${{ matrix.arch }} pip install -r requirements.txt
          arch -${{ matrix.arch }} pip install pyinstaller

      - name: Build executable
        run: |
          arch -${{ matrix.arch }} pyinstaller --onefile \
            --distpath ./dist \
            --name "tvhplayer_macos_${{ matrix.arch }}" \
            setup.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tvhplayer_macos_${{ matrix.arch }}
          path: dist/tvhplayer_macos_${{ matrix.arch }}