name: Build Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: macos
            arch: x86_64
          - os: macos-latest
            platform: macos
            arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
          - os: windows-latest
            platform: windows
            arch: x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install pyinstaller
        
      - name: Build for ${{ matrix.platform }}
        run: |
          pyinstaller --onefile \
            --distpath ./dist \
            --name "app_${GITHUB_REF_NAME}_${{ matrix.platform }}_${{ matrix.arch }}" \
            src/main.py
            
      - uses: actions/upload-artifact@v3
        with:
          name: app_${{ github.ref_name }}_${{ matrix.platform }}_${{ matrix.arch }}
          path: dist/
