name: Build and Package Binaries

on:
  push:
    tags:
      - '*'  # Trigger on tag pushes, for versioning
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ secrets.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the version from the latest tag
        id: get_version
        run: |
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable for macOS
        if: runner.os == 'macOS'
        run: |
          pyinstaller --onefile setup.py --name=tvhplayer-${{ steps.get_version.outputs.version }}-macos-intel-x86
          
      - name: Build executable for Linux
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile setup.py --name=tvhplayer-${{ steps.get_version.outputs.version }}-linux

      - name: Build executable for Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile setup.py --name=tvhplayer-${{ steps.get_version.outputs.version }}-windows.exe

      - name: Upload artifact for macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: tvhplayer-${{ steps.get_version.outputs.version }}-macos
          path: dist/tvhplayer-${{ steps.get_version.outputs.version }}-macos-intel-x86

      - name: Upload artifact for Linux
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: tvhplayer-${{ steps.get_version.outputs.version }}-linux
          path: dist/tvhplayer-${{ steps.get_version.outputs.version }}-linux

      - name: Upload artifact for Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: tvhplayer-${{ steps.get_version.outputs.version }}-windows
          path: dist/tvhplayer-${{ steps.get_version.outputs.version }}-windows.exe

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/tvhplayer-${{ steps.get_version.outputs.version }}-macos-intel-x86
            dist/tvhplayer-${{ steps.get_version.outputs.version }}-linux
            dist/tvhplayer-${{ steps.get_version.outputs.version }}-windows.exe
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ steps.get_version.outputs.version }}"
          body: "Auto-generated release for version ${{ steps.get_version.outputs.version }}"
